### ISSUE TITLE
获取作品编号格式出错

### ISSUE THREAD

**Issue by 7peanuts** [FOOLISHcode/FC2-FmagnetbyUID#1]
大佬好，获取作品编号多了个 `/article/`，应该是纯数字才对，不知道是什么原因，可能网站改版了？
如图
![20221213110551](https://user-images.githubusercontent.com/82173614/207216799-30c88463-bcff-4f6a-8c96-edffa44faada.png)

**Comment by FOOLISHcode** [comment]
这个是因为作者没有设置专有作品展示页导致，懒得弄了，手动删除一下“/”和“article”吧
